services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotshub-app
    restart: unless-stopped
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dotshub
    depends_on:
      - db
      - redis

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: dotshub-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - dotshub
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: dotshub-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-v6}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-dotshub}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init-privileges.sql:/docker-entrypoint-initdb.d/init-privileges.sql
    ports:
      - "3307:3306"
    networks:
      - dotshub

  # Redis Service
  redis:
    image: redis:alpine
    container_name: dotshub-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - dotshub

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dotshub-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME:-dotshub}
      PMA_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - dotshub
    depends_on:
      - db


# Docker Networks
networks:
  dotshub:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
